name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Check the result
      run: |
        if [ "$(python3 /home/hungry.cho/test.py)" = "hello world" ]; then
          echo "Test Passed!"
          exit 0
        else
          echo "Test failed"
          exit 1
        fi
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "main"
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_title: "Automated Pull Request" # PR 제목
        pr_body: "This is an automated PR." # PR 본문 내용
        pr_label: "automated pr" # PR에 추가할 라벨
        
